const dummies = [
  {
    id: "0",
    firstName: "Elon",
    lastName: "Musk",
    birth: "28/06/1971",
    superPower: "Brain",
    text: "testtingtestintgisttesting",
    photo: "",
  },
  {
    id: "1",
    firstName: "Jeff",
    lastName: "Bezos",
    birth: "12/01/1964",
    superPower: "Brain",
    text: "",
    photo: "",
  },
  {
    id: "2",
    firstName: "Elon",
    lastName: "Musk",
    birth: "28/06/1971",
    superPower: "Brain",
    text: "testtingtestintgisttesting",
    photo: "",
  },
  {
    id: "3",
    firstName: "Jeff",
    lastName: "Bezos",
    birth: "12/01/1964",
    superPower: "Brain",
    text: "",
    photo: "",
  },
  {
    id: "4",
    firstName: "Elon",
    lastName: "Musk",
    birth: "28/06/1971",
    superPower: "Brain",
    text: "testtingtestintgisttesting",
    photo: "",
  },
  {
    id: "5",
    firstName: "Jeff",
    lastName: "Bezos",
    birth: "12/01/1964",
    superPower: "Brain",
    text: "",
    photo: "",
  },
  {
    id: "6",
    firstName: "Elon",
    lastName: "Musk",
    birth: "28/06/1971",
    superPower: "Brain",
    text: "testtingtestintgisttesting",
    photo: "",
  },
  {
    id: "7",
    firstName: "Jeff",
    lastName: "Bezos",
    birth: "12/01/1964",
    superPower: "Brain",
    text: "",
    photo: "",
  },
  {
    id: "8",
    firstName: "Elon",
    lastName: "Musk",
    birth: "28/06/1971",
    superPower: "Brain",
    text: "testtingtestintgisttesting",
    photo: "",
  },
  {
    id: "9",
    firstName: "Jeff",
    lastName: "Bezos",
    birth: "12/01/1964",
    superPower: "Brain",
    text: "",
    photo: "",
  },
];

export default dummies;
